---

- name: install Git
  apt: name=git-core

- name: Checkout project from github
  git: repo=https://github.com/rdbwebster/vcadevops.git
       dest=/home/ubuntu/vcadevops
       accept_hostkey=yes
  sudo: yes
  sudo_user: ubuntu


#- name: Copy chef server certifiates
#  shell: scp -P {{chef_port}} ubuntu@{{chef_ip}}:/home/ubuntu/.ssh/chef-validator.pem /home/ubuntu/vcadevops/chef_repo/.chef 
#  shell: scp -P {{chef_port}} ubuntu@{{chef_ip}}:/home/ubuntu/.ssh/chef-ubuntu.pem /home/ubuntu/vcadevops/chef_repo/.chef


