---

- name: install Java 7 openjdk
  apt: name=openjdk-7-jdk update_cache=no

- name: Set JAVA HOME and PATHh values
  lineinfile:
    dest: /etc/profile
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^JAVA_HOME', line: 'JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64' }
    - { regexp: "'^export PATH=$JAVA_HOME'", line: "'export PATH=$JAVA_HOME/bin:$PATH'" }


