---

- name: Check if Jenkins is already downloaded
  stat: path=/tmp/jenkins_1.634_all.deb
  register: download_exists

- name: Get specific Jenkins Version
  shell: cd /tmp/; wget http://pkg.jenkins-ci.org/debian/binary/jenkins_1.634_all.deb
  when:  download_exists.stat.exists == False

#- name: Add Jenkins to apt source list
#  shell: wget  -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key > /tmp/key
#  shell: apt-key add  /tmp/key
#  shell: echo "deb http://pkg.jenkins-ci.org/debian binary/" >> /etc/apt/sources.list

- name: install Jenkins CI Server
#  apt: name=jenkins update_cache=yes force=yes
  apt: deb=/tmp/jenkins_1.634_all.deb state=present

- name: config
  lineinfile:
    dest: /etc/default/jenkins
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^HTTP_PORT', line: 'HTTP_PORT=8100' }
    - { regexp: '^JENKINS_USER', line: 'JENKINS_USER=ubuntu' }
    - { regexp: '^#JAVA_ARGS="-Xmx256m"', line: 'JAVA_ARGS="-Xmx256m"' }
    - { regexp: '^JAVA', line: 'JAVA="$JAVA_HOME/bin/java"' }



- name: setjava version, add before the match
  lineinfile: dest=/etc/default/jenkins 
                regexp='^JAVA'
                insertbefore='^Java'
                line='JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64'

- name: change ownership of jenkins workspaces, cache and logs
  shell: chown -R ubuntu:ubuntu /var/lib/jenkins;  chown -R ubuntu:ubuntu /var/cache/jenkins; chown -R ubuntu:ubuntu /var/log/jenkins

- name: restart jenkins service
  service: name=jenkins state=restarted

- name: add required project support files
  shell: cp /home/ubuntu/vcadevops/chef-repo/add_public_ssh_key.sh /var/lib/jenkins/add_public_ssh_key.sh

- name: add .ssh to jenkins home 
  shell: mkdir /var/lib/jenkins/.ssh; chown jenkins /var/lib/jenkins/.ssh;  chmod 700 /var/lib/jenkins/.ssh

- name: reset default jenkins user password
  shell: usermod --password $(echo $JENKINS_PASS | openssl passwd -1 -stdin) jenkins

- name: place ubuntu key in jenkins home for jenkins use to login to created servers
  shell: cp ~ubuntu/.ssh/id_rsa ~jenkins/.ssh/ubuntu_rsa; chown jenkins ~jenkins/.ssh/ubuntu_rsa;  chmod 700 ~jenkins/.ssh/ubuntu_rsa
