---


# Use curl as load through cli does not actually install plugins

- name: get Jenkins envinject plugin
  shell: cd /var/lib/jenkins/plugins/download/plugins; curl -O http://updates.jenkins-ci.org/latest/envinject.hpi

- name: get Jenkins plugin github
  shell: cd /var/lib/jenkins/plugins/download/plugins; curl -O http://updates.jenkins-ci.org/latest/github.hpi

- name: get Jenkins plugin git
  shell: cd /var/lib/jenkins/plugins/download/plugins; curl -O http://updates.jenkins-ci.org/latest/git.hpi

- name: get Jenkins plugin gitlab
  shell: cd /var/lib/jenkins/plugins/download/plugins; curl -O http://updates.jenkins-ci.org/latest/gitlab-plugin.hpi

- name: get Jenkins plugin gradle
  shell: cd /var/lib/jenkins/plugins/download/plugins; curl -O http://updates.jenkins-ci.org/latest/gradle.hpi

- name: get Jenkins plugin scps
  shell: cd /var/lib/jenkins/plugins/download/plugins; curl -O http://updates.jenkins-ci.org/latest/scp.hpi

- name: get Jenkins parameterized trigger
  shell: cd /var/lib/jenkins/plugins/download/plugins; curl -O http://updates.jenkins-ci.org/latest/parameterized-trigger.hpi

- name: safe restart jenkins
  shell: curl http://localhost:8100/reload
  #shell: java -jar jenkins-cli.jar -s {{ jenkins_url }} safe-restart

#  command: cat /var/log/jenkins/jenkins.log
#  register: log_output
#  until: log_output.stdout.find("HTTP Listener started") > -1
#  retries: 10
#  delay: 30

- name: Wait for Jenkins on 8100 
  wait_for: host=devops port=8100 delay=45

