---

- name: get jenkins cli
  shell: wget http://localhost:8100/jnlpJars/jenkins-cli.jar

- name: install required jenkins plugins
  shell: java -jar jenkins-cli.jar -s {{ jenkins_url }} install-plugin envinject github gradle

- name: safe restart jenkins
  shell: java -jar jenkins-cli.jar -s {{ jenkins_url }} safe-restart



