---

- name: install nginx package
  apt: name=nginx update_cache=yes state=latest

- name: Copy across nginx config
  template: src=devopsui_sites_available.j2 dest=/etc/nginx/sites-available/devopsui owner=root group=root  mode=0644

- name: Disable default site
  shell: rm /etc/nginx/sites-enabled/default

- name: Make devops site enabled
  shell: ln -s /etc/nginx/sites-available/devopsui /etc/nginx/sites-enabled/devopsui

- name: Restart nginx
  service: name=nginx state=restarted


