- name: Check if Selenium is already installed
  stat: path=/var/opt/selenium
  register: download_dir_exists

- name: download selenium
  shell: mkdir /var/opt/selenium; cd /var/opt/selenium; wget http://goo.gl/PJUZfa
  when:  download_dir_exists.stat.exists == False

- name: Copy across upstart service config for selenium
  template: src=selenium.conf.j2 dest=/etc/init/selenium.conf owner=root group=root  mode=0644

- name: Start Service
  service: name=selenium state=restarted

