
- name: Set some ssh timeout valuesk
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^ClientAliveInterval', line: 'ClientAliveInterval 600' }
    - { regexp: '^ClientAliveCountMax', line: 'ClientAliveCountMax 3' }

- name: Install sshpass
  apt: name=sshpass update_cache=yes


