---

- name: build-essential
  apt: name=build-essential update_cache=no

- name: libssl-dev 
  apt: name=libssl-dev update_cache=no

- name: libffi-dev 
  apt: name=libffi-dev update_cache=no

- name: libxml2-dev 
  apt: name=libxml2-dev update_cache=no

- name: libxslt-dev 
  apt: name=libxslt-dev update_cache=no

- name: python-dev 
  apt: name=python-dev update_cache=no

#- name: python-pip 
#  apt: name=python-pip update_cache=yes

- name: Install python-tools
  apt:  name=python-setuptools

- name: Install pip with easy-install to avoid 'cannot import name IncompleteRead' Error
  shell: easy_install -U pip 

- name: Install vca-cli
  shell: pip install vca-cli==10rc8

